[package]
name = "boleta"
version = "0.1.0"
authors = ["Pablo Opazo <pablo@d@sequel.ninja>"]

[dependencies]
yaml-rust = "*"
curl-easybuilder = "0.1"
clap = "2.20.5"
chrono = "0.3"
text_io = "0.1.6"

